server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medicineinventory
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

app:
  jwtExpirationInMs: 10800000
