server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medicineinventory
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.office365.com
    username: jaydeeptomal@hotmail.com
    password: jayrimpi1991
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwtExpirationInMs: 10800000

